server:
    port: 8080

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: 127.10.49.2
            port: 27017
            database: nosmoke
    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: oculuservice

http:
    cache:
        timeToLiveInDays: 31


